### PR TITLE
PHP 8.3 support added

### PR DESCRIPTION
**Pull request by glo71317**
|    Q          |   A
|-------------- | ------
| Documentation | yes/no
| Bugfix        | yes/no
| BC Break      | yes/no
| New Feature   | yes/no
| RFC           | yes/no
| QA            | yes/no

### CODE REVIEW

**Comment by glo71317** [comment]
Hi,
it seems php8.3_igbinary stable version is not available.
Screenshot 2023-10-12 at 3 34 52 PM
@boesing Anything we can do for fix this?

**Comment by glo17680** [comment]
@boesing - any plan to fix this issue or anything can we do. Can you please advise?

**Comment by froschdesign** [comment]
@glo17680
Here we have to wait: "E: Couldn't find any package by glob 'php8.3-igbinary'"
The psalm errors can already be fixed:

https://github.com/laminas/laminas-serializer/actions/runs/6494179022/job/18073771144?pr=59#step:3:360

**Comment by boesing** [comment]
Installing extensions via pecl could be a way. we tend to do so in pre-install scripts. done that recently somewhere, maybe check the 8.3 project, I definitely had to install an extension for 8.3 due to missing in sury upstream.

Update: did it here, you can adapt the changes for this PR tho - https://github.com/laminas/laminas-serializer/pull/49

**Comment by boesing** [comment]
Closing here as v2.17 already has 8.3 support. maybe the merge-up only applied to v3.
I'll merge-up v2.17.0 in 2.18.x which makes this PR superseded.

**Pull request closed without merging**
