### PR TITLE
Add support for PHP 8.3

### PR DESCRIPTION
**Pull request by MauricioFauth**
|    Q          |   A
|-------------- | ------
| New Feature   | yes

### Description

Adds support for PHP 8.3.

### CODE REVIEW

**Comment by MauricioFauth** [comment]
Looks like the `php8.3-igbinary` and `php8.3-msgpack` extensions are not available yet. Since those extensions are optional, shouldn't the CI test with and without them?

**Comment by boesing** [comment]
> Since those extensions are optional, shouldn't the CI test with and without them?

They are optional, indeed. 
But they're optional for upstream projects. IMHO required for CI since shipping stuff without proper support for optional stuff is not how it should work.
We might be able to install extensions via PECL.

**Comment by MauricioFauth** [comment]
> But they're optional for upstream projects. IMHO required for CI since shipping stuff without proper support for optional stuff is not how it should work.

Yeah, I agree with testing with the extensions. I meant to also test without the extensions to see if the rest of the library properly works when the optional extensions are not installed.

**Comment by boesing** [comment]
Thats definitely something we could do, but that would most likely require to re-configure the checks made by this project.
Not sure if its worth the hassle as it would be almost impossible to determine which extensions are required and which are optional (ofc. one could check the `composer.json`).

Might be more beneficial if we simply ignore uninstallable extensions instead of failing hard. Can you create a feature request in the CI container action? That would be helpful, I'll manage to make the tests pass.
Already on a fix for the `pecl` issue in https://github.com/laminas/laminas-continuous-integration-action/pull/189

**Comment by boesing** [comment]
Thanks, @MauricioFauth!

**Pull request merged**
